In [ ]:
   # Enter your own info here. If you use mine, it will run out
api_key ='acc_450404a38b9df17'
api_secret = '449c0b22c9154cbc9762419a45905e65'
authorization = 'Basic YWNjXzQ1MDQwNGEzOGI5ZGYxNzo0NDljMGIyMmM5MTU0Y2JjOTc2MjQxOWE0NTkwNWU2NQ=='
endpoint ='https://api.imagga.com'

In [ ]:
import requests
import json
    
url = 'https://api.imagga.com/v2/tags/?image_url=https://www.ishelp.info/data/images/'
images = ['3_628913364622688256.jpg', '3_628933195636047872.jpg']

for image in images:
  request = requests.get(url + image, auth=(api_key, api_secret))
  json_data = json.loads(request.text)
  clean_data = json.dumps(json_data, indent=2)
  print(f"{clean_data}")

In [ ]:
response = requests.get('https://api.imagga.com/v2/categorizers', auth=(api_key, api_secret))
json_data = json.loads(response.text)
clean_data = json.dumps(json_data, indent=2)
print(f"{clean_data}")

In [ ]:
import pandas as pd

df = pd.DataFrame(columns=["interior objects", "nature landscape", "beaches seaside", "events parties", "food drinks", 
                            "paintings art", "pets animals", "text visuals", "sunrises sunsets", "cars vehicles", 
                            "macro flowers", "streetview architecture", "people portraits"])
  
url = 'https://api.imagga.com/v2/categories/personal_photos/?image_url=https://www.ishelp.info/data/images/'
images = ['3_628913364622688256.jpg', '3_628933195636047872.jpg']

for image in images:
  request = requests.get(url + image, auth=(api_key, api_secret))
  json_data = json.loads(request.text)
  print(json.dumps(json_data, indent=2))

  # Create a list of 0.0 scores to update as we get data for each category we want to score in our DataFrame
  scores = [0.0] * len(df.columns)

  # Iterate through each category of the result
  for category in json_data["result"]["categories"]:
    # Find the associated column in the DataFrame
    for n, col in enumerate(df.columns):
      if col == category['name']['en']:
        # Store the score
        scores[n] = category['confidence']
        break # No need to keep looping once we've found the score

    # Store the list as a new row in the DataFrame
    df.loc[image] = scores

In [ ]:
df

                          interior objects  ...  people portraits
3_628913364622688256.jpg               0.0  ...         78.222015
3_628933195636047872.jpg               0.0  ...         73.763931

[2 rows x 13 columns]